osx_image: xcode9
language: swift
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/ProgressMeter.xcworkspace -scheme ProgressMeter-Example -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint